% =====================================================================================================================
% Function which initialize cell arrays to match the enum data types found in the SimCorTcp library.
%
% $LastChangedDate$ 
% $Author$
% =====================================================================================================================
function init = InitStates()
% This array needs to match
% org.nees.uiuc.simcor.transaction.Transaction.TransactionStateNames
init.transactionStates = {...
    'COMMAND_AVAILABLE',...
    'ERRORS_EXIST',...
    'READ_COMMAND',...
    'READ_RESPONSE',...
    'RESPONSE_AVAILABLE',...
    'SENDING_COMMAND',...
    'SENDING_RESPONSE',...
    'TRANSACTION_DONE',...
    'WAIT_FOR_COMMAND',...
    'WAIT_FOR_RESPONSE'...
    };

% This array needs to match
% org.nees.uiuc.simcor.tcp.Connection.ConnectionState
init.connectionStates = {'READY','BUSY','IN_ERROR','CLOSED'};

% This array needs to match org.nees.simcor.transaction.SimCorMsg.MsgType
init.msgTypes = {'COMMAND', 'NOT_OK_RESPONSE', 'OK_RESPONSE'};
end